name: CI

on: [push]

jobs:
  sast_scan:
    name: Bearer Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Bearer
      uses: bearer/bearer-action@v2
      with:
        format: sarif
        output: results.sarif

    - name: Upload SARIF file
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif


    - name: Upload SARIF as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bearer-sarif
        path: results.sarif

